/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 04-abr.-2019 01:23:58 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

-- CREATE DATABASE sibdd;
USE sibdd;

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Articulos` CASCADE;

DROP TABLE IF EXISTS `Categorias` CASCADE;

DROP TABLE IF EXISTS `Clientes_Domicilios` CASCADE;

DROP TABLE IF EXISTS `Clientes_Telefonos` CASCADE;

DROP TABLE IF EXISTS `Clientes` CASCADE;

DROP TABLE IF EXISTS `Detalles_Pedidos` CASCADE;

DROP TABLE IF EXISTS `Domicilios` CASCADE;

DROP TABLE IF EXISTS `Marcas` CASCADE;

DROP TABLE IF EXISTS `Pedidos` CASCADE;

DROP TABLE IF EXISTS `Proveedores_Telefonos` CASCADE;

DROP TABLE IF EXISTS `Proveedores` CASCADE;

DROP TABLE IF EXISTS `Sucursales_Telefonos` CASCADE;

DROP TABLE IF EXISTS `Sucursales_Domicilio` CASCADE;

DROP TABLE IF EXISTS `Sucursales` CASCADE;

DROP TABLE IF EXISTS `Telefonos` CASCADE;

DROP TABLE IF EXISTS `Tipo_Pagos` CASCADE;

DROP TABLE IF EXISTS `Ventas_Cabecera` CASCADE;

DROP TABLE IF EXISTS `Ventas_Detalle` CASCADE;

/* Create Tables */
-- •

CREATE TABLE `Categorias`
(
	`id_categoria` INT NOT NULL AUTO_INCREMENT,
	`categoria` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_categoria` ASC)
);

-- •
CREATE TABLE `Marcas`
(
	`id_marca` INT NOT NULL AUTO_INCREMENT,
	`marca` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_marca` ASC)
);

-- •
CREATE TABLE `Articulos`
(
	`id_articulo` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`descripcion` VARCHAR(50) NOT NULL,
	`id_categoria` INT NOT NULL,
	`id_marca` INT NOT NULL,
	`precio_unitario` DOUBLE(10,2) NOT NULL,
	`existencia` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_articulo` ASC)
);

-- •
CREATE TABLE `Clientes`
(
	`id_cliente` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NULL,
	`email` VARCHAR(50) NOT NULL,
	`rfc` VARCHAR(50) NOT NULL,
	`procentaje_descuento` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_cliente` ASC)
);

-- •
CREATE TABLE `Domicilios`
(
	`id_domicilio` INT NOT NULL AUTO_INCREMENT,
	`numero` VARCHAR(6) NOT NULL,
	`calle` VARCHAR(50) NOT NULL,
	`colonia` VARCHAR(50) NOT NULL,
	`municipio` VARCHAR(50) NOT NULL,
	`estado` VARCHAR(50) NOT NULL,
	`pais` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_domicilio` ASC)
);

-- •
CREATE TABLE `Telefonos`
(
	`id_telefono` INT NOT NULL AUTO_INCREMENT,
	`telefono` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_telefono` ASC)
);

-- •
CREATE TABLE `Clientes_Domicilios`
(
	`id_cliente` INT NOT NULL,
	`id_domicilio` INT NOT NULL
);

-- •
CREATE TABLE `Clientes_Telefonos`
(
	`id_cliente` INT NOT NULL,
	`id_telefono` INT NOT NULL
);

-- •
CREATE TABLE `Tipo_Pagos`
(
	`id_tipo_pago` INT NOT NULL AUTO_INCREMENT,
	`tipo_pago` VARCHAR(50) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_tipo_pago` ASC)
);

-- •
CREATE TABLE `Pedidos`
(
	`id_pedido` INT NOT NULL AUTO_INCREMENT,
	`fecha_pedido` DATE NOT NULL,
	`fecha_entrega` DATE NOT NULL,
	`id_tipo_pago` INT NOT NULL,
	`costo_total` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_pedido` ASC)
);

-- •
CREATE TABLE `Detalles_Pedidos`
(
	`id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
	`id_proveedor` INT NOT NULL,
	`id_articulo` INT NOT NULL,
	`cantidad` INT NOT NULL,
	`id_pedido` INT NOT NULL,
	`costo_total_por_producto` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Detalle_Pedidos` PRIMARY KEY (`id_detalle_pedido` ASC)
);

-- •
CREATE TABLE `Proveedores`
(
	`id_proveedor` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`fax` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`rfc` VARCHAR(50) NOT NULL,
	`id_domicilio` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_proveedor` ASC)
);

-- •
CREATE TABLE `Proveedores_Telefonos`
(
	`id_proveedor` INT NOT NULL,
	`id_telefono` INT NOT NULL
);

-- •
CREATE TABLE `Sucursales`
(
	`id_sucursal` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_sucursal` ASC)
);

-- •
CREATE TABLE `Sucursales_Telefonos`
(
	`id_sucursal` INT NOT NULL,
	`id_telefono` INT NOT NULL
);

-- •
CREATE TABLE `Sucursales_Domicilios`
(
	`id_sucursal` INT NOT NULL,
	`id_domicilio` INT NOT NULL
);

-- •
CREATE TABLE `Ventas_Cabecera`
(
	`id_venta_cabecera` INT NOT NULL AUTO_INCREMENT,
	`id_cliente` INT NOT NULL,
	`id_sucursal` INT NOT NULL,
	`fecha` DATE NOT NULL,
	`precio_total` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_venta_cabecera` ASC)
)

;

-- •
CREATE TABLE `Ventas_Detalle`
(
	`id_venta_detalle` INT NOT NULL AUTO_INCREMENT,
	`id_articulo` INT NOT NULL,
	`cantidad` INT NOT NULL,
	`precio_total_por_producto` DOUBLE(10,2) NOT NULL,
	`id_venta_cabecera` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_venta_detalle` ASC)
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Articulos` 
 ADD CONSTRAINT `unique_nombre` UNIQUE (`nombre` ASC);

ALTER TABLE `Articulos` 
 ADD INDEX `IXFK_Articulos_Categorias` (`id_categoria` ASC);

ALTER TABLE `Articulos` 
 ADD INDEX `IXFK_Articulos_Marcas` (`id_marca` ASC);

ALTER TABLE `Clientes_Domicilios` 
 ADD INDEX `IXFK_Cliente_Domicilio_Clientes` (`id_cliente` ASC);

ALTER TABLE `Clientes_Domicilios` 
 ADD INDEX `IXFK_Cliente_Domicilio_Domicilios` (`id_domicilio` ASC);

ALTER TABLE `Clientes_Telefonos` 
 ADD INDEX `IXFK_Cliente_Telefono_Clientes` (`id_cliente` ASC);

ALTER TABLE `Clientes_Telefonos` 
 ADD INDEX `IXFK_Cliente_Telefono_Telefonos` (`id_telefono` ASC);

ALTER TABLE `Detalles_Pedidos` 
 ADD INDEX `IXFK_Detalle_Pedidos_Articulos` (`id_articulo` ASC);

ALTER TABLE `Detalles_Pedidos` 
 ADD INDEX `IXFK_Detalle_Pedidos_Pedidos` (`id_pedido` ASC);

ALTER TABLE `Detalles_Pedidos` 
 ADD INDEX `IXFK_Detalle_Pedidos_Proveedores` (`id_proveedor` ASC);

ALTER TABLE `Pedidos` 
 ADD INDEX `IXFK_Pedidos_Tipo_Pago` (`id_tipo_pago` ASC);

ALTER TABLE `Proveedores_Telefonos` 
 ADD INDEX `IXFK_Proveedor_Telefono_Proveedores` (`id_proveedor` ASC);

ALTER TABLE `Proveedores_Telefonos` 
 ADD INDEX `IXFK_Proveedor_Telefono_Telefonos` (`id_telefono` ASC);

ALTER TABLE `Proveedores` 
 ADD INDEX `IXFK_Proveedores_Domicilios` (`id_domicilio` ASC);

ALTER TABLE `Sucursales_Telefonos` 
 ADD INDEX `IXFK_Sucursales_Telefono_Sucursales` (`id_sucursal` ASC);

ALTER TABLE `Sucursales_Telefonos` 
 ADD INDEX `IXFK_Sucursales_Telefonos_Telefonos` (`id_telefono` ASC);

ALTER TABLE `Sucursales_Domicilios` 
 ADD INDEX `IXFK_Sucursales_Domicilios_Domicilios` (`id_domicilio` ASC);

ALTER TABLE `Sucursales_Domicilios` 
 ADD INDEX `IXFK_Sucursales_Domicilios_Sucursales` (`id_sucursal` ASC);

ALTER TABLE `Ventas_Cabecera` 
 ADD INDEX `IXFK_Ventas_Cabecera_Clientes` (`id_cliente` ASC);

ALTER TABLE `Ventas_Cabecera` 
 ADD INDEX `IXFK_Ventas_Cabecera_Sucursales` (`id_sucursal` ASC);

ALTER TABLE `Ventas_Detalle` 
 ADD INDEX `IXFK_Ventas_Detalle_Articulos` (`id_articulo` ASC);

ALTER TABLE `Ventas_Detalle` 
 ADD INDEX `IXFK_Ventas_Detalle_Ventas_Cabecera` (`id_venta_cabecera` ASC);

/* Create Foreign Key Constraints */

ALTER TABLE `Articulos` 
 ADD CONSTRAINT `FK_Articulos_Categorias`
	FOREIGN KEY (`id_categoria`) REFERENCES `Categorias` (`id_categoria`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Articulos` 
 ADD CONSTRAINT `FK_Articulos_Marcas`
	FOREIGN KEY (`id_marca`) REFERENCES `Marcas` (`id_marca`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Domicilios` 
 ADD CONSTRAINT `FK_Cliente_Domicilio_Clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `Clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Domicilios` 
 ADD CONSTRAINT `FK_Cliente_Domicilio_Domicilios`
	FOREIGN KEY (`id_domicilio`) REFERENCES `Domicilios` (`id_domicilio`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Telefonos` 
 ADD CONSTRAINT `FK_Cliente_Telefono_Clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `Clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Telefonos` 
 ADD CONSTRAINT `FK_Cliente_Telefono_Telefonos`
	FOREIGN KEY (`id_telefono`) REFERENCES `Telefonos` (`id_telefono`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Detalles_Pedidos` 
 ADD CONSTRAINT `FK_Detalle_Pedidos_Articulos`
	FOREIGN KEY (`id_articulo`) REFERENCES `Articulos` (`id_articulo`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Detalles_Pedidos` 
 ADD CONSTRAINT `FK_Detalle_Pedidos_Pedidos`
	FOREIGN KEY (`id_pedido`) REFERENCES `Pedidos` (`id_pedido`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Detalles_Pedidos` 
 ADD CONSTRAINT `FK_Detalle_Pedidos_Proveedores`
	FOREIGN KEY (`id_proveedor`) REFERENCES `Proveedores` (`id_proveedor`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Pedidos` 
 ADD CONSTRAINT `FK_Pedidos_TipoPago`
	FOREIGN KEY (`id_tipo_pago`) REFERENCES `Tipo_Pagos` (`id_tipo_pago`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Proveedores_Telefonos` 
 ADD CONSTRAINT `FK_Proveedor_Telefono_Proveedores`
	FOREIGN KEY (`id_proveedor`) REFERENCES `Proveedores` (`id_proveedor`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Proveedores_Telefonos` 
 ADD CONSTRAINT `FK_Proveedor_Telefono_Telefonos`
	FOREIGN KEY (`id_telefono`) REFERENCES `Telefonos` (`id_telefono`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Proveedores` 
 ADD CONSTRAINT `FK_Proveedores_Domicilios`
	FOREIGN KEY (`id_domicilio`) REFERENCES `Domicilios` (`id_domicilio`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Telefonos` 
 ADD CONSTRAINT `FK_Sucursal_Telefono_Sucursales`
	FOREIGN KEY (`id_sucursal`) REFERENCES `Sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Telefonos` 
 ADD CONSTRAINT `FK_Sucursal_Telefono_Telefonos`
	FOREIGN KEY (`id_telefono`) REFERENCES `Telefonos` (`id_telefono`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Domicilios` 
 ADD CONSTRAINT `FK_Sucursale_Domicilio_Domicilios`
	FOREIGN KEY (`id_domicilio`) REFERENCES `Domicilios` (`id_domicilio`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Domicilios` 
 ADD CONSTRAINT `FK_Sucursale_Domicilio_Sucursales`
	FOREIGN KEY (`id_sucursal`) REFERENCES `Sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Cabecera` 
 ADD CONSTRAINT `FK_Ventas_Cabecera_Clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `Clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Cabecera` 
 ADD CONSTRAINT `FK_Ventas_Cabecera_Sucursales`
	FOREIGN KEY (`id_sucursal`) REFERENCES `Sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Detalle` 
 ADD CONSTRAINT `FK_Ventas_Detalle_Articulos`
	FOREIGN KEY (`id_articulo`) REFERENCES `Articulos` (`id_articulo`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Detalle` 
 ADD CONSTRAINT `FK_Ventas_Detalle_Ventas_Cabecera`
	FOREIGN KEY (`id_venta_cabecera`) REFERENCES `Ventas_Cabecera` (`id_venta_cabecera`) ON DELETE Restrict ON UPDATE Restrict;

SET FOREIGN_KEY_CHECKS=1;
