/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 04-abr.-2019 01:23:58 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE sibdd;

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Articulos` CASCADE;

DROP TABLE IF EXISTS `Categorias` CASCADE;

DROP TABLE IF EXISTS `Clientes_Domicilios` CASCADE;

DROP TABLE IF EXISTS `Clientes_Telefonos` CASCADE;

DROP TABLE IF EXISTS `Clientes` CASCADE;

DROP TABLE IF EXISTS `Detalles_Pedidos` CASCADE;

DROP TABLE IF EXISTS `Domicilios` CASCADE;

DROP TABLE IF EXISTS `Marcas` CASCADE;

DROP TABLE IF EXISTS `Pedidos` CASCADE;

DROP TABLE IF EXISTS `Proveedores_Telefonos` CASCADE;

DROP TABLE IF EXISTS `Proveedores` CASCADE;

DROP TABLE IF EXISTS `Sucursales_Telefonos` CASCADE;

DROP TABLE IF EXISTS `Sucursales_Domicilio` CASCADE;

DROP TABLE IF EXISTS `Sucursales` CASCADE;

DROP TABLE IF EXISTS `Telefonos` CASCADE;

DROP TABLE IF EXISTS `Tipo_Pagos` CASCADE;

DROP TABLE IF EXISTS `Ventas_Cabecera` CASCADE;

DROP TABLE IF EXISTS `Ventas_Detalle` CASCADE;

/* Create Tables */
-- •

CREATE TABLE `Categorias`
(
	`id_categoria` INT NOT NULL AUTO_INCREMENT,
	`categoria` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_categoria` ASC)
);

-- •
CREATE TABLE `Marcas`
(
	`id_marca` INT NOT NULL AUTO_INCREMENT,
	`marca` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_marca` ASC)
);

-- •
CREATE TABLE `Articulos`
(
	`id_articulo` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`descripcion` VARCHAR(50) NOT NULL,
	`id_categoria` INT NOT NULL,
	`id_marca` INT NOT NULL,
	`precio_unitario` DOUBLE(10,2) NOT NULL,
	`existencia` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_articulo` ASC)
);

-- •
CREATE TABLE `Clientes`
(
	`id_cliente` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NULL,
	`email` VARCHAR(50) NOT NULL,
	`rfc` VARCHAR(50) NOT NULL,
	`procentaje_descuento` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_cliente` ASC)
);

-- •
CREATE TABLE `Domicilios`
(
	`id_domicilio` INT NOT NULL AUTO_INCREMENT,
	`numero` VARCHAR(6) NOT NULL,
	`calle` VARCHAR(50) NOT NULL,
	`colonia` VARCHAR(50) NOT NULL,
	`municipio` VARCHAR(50) NOT NULL,
	`estado` VARCHAR(50) NOT NULL,
	`pais` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_domicilio` ASC)
);

-- •
CREATE TABLE `Telefonos`
(
	`id_telefono` INT NOT NULL AUTO_INCREMENT,
	`telefono` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_telefono` ASC)
);

-- •
CREATE TABLE `Clientes_Domicilios`
(
	`id_cliente` INT NOT NULL,
	`id_domicilio` INT NOT NULL
);

-- •
CREATE TABLE `Clientes_Telefonos`
(
	`id_cliente` INT NOT NULL,
	`id_telefono` INT NOT NULL
);

-- •
CREATE TABLE `Tipo_Pagos`
(
	`id_tipo_pago` INT NOT NULL AUTO_INCREMENT,
	`tipo_pago` VARCHAR(50) NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_tipo_pago` ASC)
);

-- •
CREATE TABLE `Pedidos`
(
	`id_pedido` INT NOT NULL AUTO_INCREMENT,
	`fecha_pedido` DATE NOT NULL,
	`fecha_entrega` DATE NOT NULL,
	`id_tipo_pago` INT NOT NULL,
	`costo_total` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_pedido` ASC)
);

-- •
CREATE TABLE `Detalles_Pedidos`
(
	`id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
	`id_proveedor` INT NOT NULL,
	`id_articulo` INT NOT NULL,
	`cantidad` INT NOT NULL,
	`id_pedido` INT NOT NULL,
	`costo_total_por_producto` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Detalle_Pedidos` PRIMARY KEY (`id_detalle_pedido` ASC)
);

-- •
CREATE TABLE `Proveedores`
(
	`id_proveedor` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`fax` VARCHAR(50) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`rfc` VARCHAR(50) NOT NULL,
	`id_domicilio` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_proveedor` ASC)
);

-- •
CREATE TABLE `Proveedores_Telefonos`
(
	`id_proveedor` INT NOT NULL,
	`id_telefono` INT NOT NULL
);

-- •
CREATE TABLE `Sucursales`
(
	`id_sucursal` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_sucursal` ASC)
);

-- •
CREATE TABLE `Sucursales_Telefonos`
(
	`id_sucursal` INT NOT NULL,
	`id_telefono` INT NOT NULL
);

-- •
CREATE TABLE `Sucursales_Domicilios`
(
	`id_sucursal` INT NOT NULL,
	`id_domicilio` INT NOT NULL
);

-- •
CREATE TABLE `Ventas_Cabecera`
(
	`id_venta_cabecera` INT NOT NULL AUTO_INCREMENT,
	`id_cliente` INT NOT NULL,
	`id_sucursal` INT NOT NULL,
	`fecha` DATE NOT NULL,
	`precio_total` DOUBLE(10,2) NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_venta_cabecera` ASC)
)

;

-- •
CREATE TABLE `Ventas_Detalle`
(
	`id_venta_detalle` INT NOT NULL AUTO_INCREMENT,
	`id_articulo` INT NOT NULL,
	`cantidad` INT NOT NULL,
	`precio_total_por_producto` DOUBLE(10,2) NOT NULL,
	`id_venta_cabecera` INT NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`id_venta_detalle` ASC)
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Articulos` 
 ADD CONSTRAINT `unique_nombre` UNIQUE (`nombre` ASC);

ALTER TABLE `Articulos` 
 ADD INDEX `IXFK_Articulos_Categorias` (`id_categoria` ASC);

ALTER TABLE `Articulos` 
 ADD INDEX `IXFK_Articulos_Marcas` (`id_marca` ASC);

ALTER TABLE `Clientes_Domicilios` 
 ADD INDEX `IXFK_Cliente_Domicilio_Clientes` (`id_cliente` ASC);

ALTER TABLE `Clientes_Domicilios` 
 ADD INDEX `IXFK_Cliente_Domicilio_Domicilios` (`id_domicilio` ASC);

ALTER TABLE `Clientes_Telefonos` 
 ADD INDEX `IXFK_Cliente_Telefono_Clientes` (`id_cliente` ASC);

ALTER TABLE `Clientes_Telefonos` 
 ADD INDEX `IXFK_Cliente_Telefono_Telefonos` (`id_telefono` ASC);

ALTER TABLE `Detalles_Pedidos` 
 ADD INDEX `IXFK_Detalle_Pedidos_Articulos` (`id_articulo` ASC);

ALTER TABLE `Detalles_Pedidos` 
 ADD INDEX `IXFK_Detalle_Pedidos_Pedidos` (`id_pedido` ASC);

ALTER TABLE `Detalles_Pedidos` 
 ADD INDEX `IXFK_Detalle_Pedidos_Proveedores` (`id_proveedor` ASC);

ALTER TABLE `Pedidos` 
 ADD INDEX `IXFK_Pedidos_Tipo_Pago` (`id_tipo_pago` ASC);

ALTER TABLE `Proveedores_Telefonos` 
 ADD INDEX `IXFK_Proveedor_Telefono_Proveedores` (`id_proveedor` ASC);

ALTER TABLE `Proveedores_Telefonos` 
 ADD INDEX `IXFK_Proveedor_Telefono_Telefonos` (`id_telefono` ASC);

ALTER TABLE `Proveedores` 
 ADD INDEX `IXFK_Proveedores_Domicilios` (`id_domicilio` ASC);

ALTER TABLE `Sucursales_Telefonos` 
 ADD INDEX `IXFK_Sucursales_Telefono_Sucursales` (`id_sucursal` ASC);

ALTER TABLE `Sucursales_Telefonos` 
 ADD INDEX `IXFK_Sucursales_Telefonos_Telefonos` (`id_telefono` ASC);

ALTER TABLE `Sucursales_Domicilios` 
 ADD INDEX `IXFK_Sucursales_Domicilios_Domicilios` (`id_domicilio` ASC);

ALTER TABLE `Sucursales_Domicilios` 
 ADD INDEX `IXFK_Sucursales_Domicilios_Sucursales` (`id_sucursal` ASC);

ALTER TABLE `Ventas_Cabecera` 
 ADD INDEX `IXFK_Ventas_Cabecera_Clientes` (`id_cliente` ASC);

ALTER TABLE `Ventas_Cabecera` 
 ADD INDEX `IXFK_Ventas_Cabecera_Sucursales` (`id_sucursal` ASC);

ALTER TABLE `Ventas_Detalle` 
 ADD INDEX `IXFK_Ventas_Detalle_Articulos` (`id_articulo` ASC);

ALTER TABLE `Ventas_Detalle` 
 ADD INDEX `IXFK_Ventas_Detalle_Ventas_Cabecera` (`id_venta_cabecera` ASC);

/* Create Foreign Key Constraints */

ALTER TABLE `Articulos` 
 ADD CONSTRAINT `FK_Articulos_Categorias`
	FOREIGN KEY (`id_categoria`) REFERENCES `Categorias` (`id_categoria`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Articulos` 
 ADD CONSTRAINT `FK_Articulos_Marcas`
	FOREIGN KEY (`id_marca`) REFERENCES `Marcas` (`id_marca`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Domicilios` 
 ADD CONSTRAINT `FK_Cliente_Domicilio_Clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `Clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Domicilios` 
 ADD CONSTRAINT `FK_Cliente_Domicilio_Domicilios`
	FOREIGN KEY (`id_domicilio`) REFERENCES `Domicilios` (`id_domicilio`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Telefonos` 
 ADD CONSTRAINT `FK_Cliente_Telefono_Clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `Clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Clientes_Telefonos` 
 ADD CONSTRAINT `FK_Cliente_Telefono_Telefonos`
	FOREIGN KEY (`id_telefono`) REFERENCES `Telefonos` (`id_telefono`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Detalles_Pedidos` 
 ADD CONSTRAINT `FK_Detalle_Pedidos_Articulos`
	FOREIGN KEY (`id_articulo`) REFERENCES `Articulos` (`id_articulo`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Detalles_Pedidos` 
 ADD CONSTRAINT `FK_Detalle_Pedidos_Pedidos`
	FOREIGN KEY (`id_pedido`) REFERENCES `Pedidos` (`id_pedido`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Detalles_Pedidos` 
 ADD CONSTRAINT `FK_Detalle_Pedidos_Proveedores`
	FOREIGN KEY (`id_proveedor`) REFERENCES `Proveedores` (`id_proveedor`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Pedidos` 
 ADD CONSTRAINT `FK_Pedidos_TipoPago`
	FOREIGN KEY (`id_tipo_pago`) REFERENCES `Tipo_Pagos` (`id_tipo_pago`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Proveedores_Telefonos` 
 ADD CONSTRAINT `FK_Proveedor_Telefono_Proveedores`
	FOREIGN KEY (`id_proveedor`) REFERENCES `Proveedores` (`id_proveedor`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Proveedores_Telefonos` 
 ADD CONSTRAINT `FK_Proveedor_Telefono_Telefonos`
	FOREIGN KEY (`id_telefono`) REFERENCES `Telefonos` (`id_telefono`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Proveedores` 
 ADD CONSTRAINT `FK_Proveedores_Domicilios`
	FOREIGN KEY (`id_domicilio`) REFERENCES `Domicilios` (`id_domicilio`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Telefonos` 
 ADD CONSTRAINT `FK_Sucursal_Telefono_Sucursales`
	FOREIGN KEY (`id_sucursal`) REFERENCES `Sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Telefonos` 
 ADD CONSTRAINT `FK_Sucursal_Telefono_Telefonos`
	FOREIGN KEY (`id_telefono`) REFERENCES `Telefonos` (`id_telefono`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Domicilios` 
 ADD CONSTRAINT `FK_Sucursale_Domicilio_Domicilios`
	FOREIGN KEY (`id_domicilio`) REFERENCES `Domicilios` (`id_domicilio`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Sucursales_Domicilios` 
 ADD CONSTRAINT `FK_Sucursale_Domicilio_Sucursales`
	FOREIGN KEY (`id_sucursal`) REFERENCES `Sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Cabecera` 
 ADD CONSTRAINT `FK_Ventas_Cabecera_Clientes`
	FOREIGN KEY (`id_cliente`) REFERENCES `Clientes` (`id_cliente`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Cabecera` 
 ADD CONSTRAINT `FK_Ventas_Cabecera_Sucursales`
	FOREIGN KEY (`id_sucursal`) REFERENCES `Sucursales` (`id_sucursal`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Detalle` 
 ADD CONSTRAINT `FK_Ventas_Detalle_Articulos`
	FOREIGN KEY (`id_articulo`) REFERENCES `Articulos` (`id_articulo`) ON DELETE Restrict ON UPDATE Restrict;

ALTER TABLE `Ventas_Detalle` 
 ADD CONSTRAINT `FK_Ventas_Detalle_Ventas_Cabecera`
	FOREIGN KEY (`id_venta_cabecera`) REFERENCES `Ventas_Cabecera` (`id_venta_cabecera`) ON DELETE Restrict ON UPDATE Restrict;

SET FOREIGN_KEY_CHECKS=1;

/* 
1. Se debe generar una función que dado el nombre de un artículo te 
regrese el proveedor al que más le has comprado ese artículo, 
el mejor precio que te ha dado ese proveedor para ese artículo, 
el precio más alto que te ha dado y el último precio. Los precios 
deben ser en formato moneda
*/

DELIMITER $$
CREATE OR REPLACE PROCEDURE Funcion1(IN nombre_articulo VARCHAR(50))
BEGIN
    SELECT 
        p.nombre, 
        COUNT(p.nombre) maximo, 
        a.nombre, SUM(dp.cantidad), 
        MIN(dp.costo_total_por_producto / dp.cantidad) MEJOR_PRECIO, 
        MAX(dp.costo_total_por_producto / dp.cantidad) PRECIO_MAS_ALTO, 
        (SELECT
            dp.costo_total_por_producto / dp.cantidad 
        FROM Detalles_Pedidos dp 
        INNER JOIN Articulos a 
        ON dp.id_articulo = a.id_articulo 
        WHERE dp.id_detalle_pedido = (SELECT MAX(dp.id_detalle_pedido) 
            FROM Detalles_Pedidos dp 
            INNER JOIN Articulos a 
            ON dp.id_articulo = a.id_articulo 
            WHERE a.nombre = nombre_articulo)) ULTIMO_PRECIO 
    FROM Detalles_Pedidos dp 
    INNER JOIN Proveedores p 
    ON dp.id_proveedor = p.id_proveedor
    INNER JOIN Articulos a 
    ON dp.id_articulo = a.id_articulo 
    WHERE a.nombre = nombre_articulo
    GROUP BY p.nombre
    ORDER BY maximo DESC LIMIT 1;
END $$

DELIMITER ;

/*
2. Se debe generar una función que dado el nombre de un cliente 
te devuelva: El producto que más ha comprado, 
el producto que menos ha comprado, 
la sucursal en la que más compra y la cantidad de su compra más alta 
*/
DELIMITER $$
CREATE OR REPLACE PROCEDURE Funcion2(IN nombre_cliente VARCHAR(50))
BEGIN

    DECLARE unoNombre VARCHAR(50);
    DECLARE unoTotal INT unsigned DEFAULT 0;
    DECLARE dosNombre VARCHAR(50);
    DECLARE dosTotal INT unsigned DEFAULT 0;
    DECLARE tresNombre VARCHAR(50);
    DECLARE cuatroTotal DOUBLE unsigned DEFAULT 0.0;

    SELECT
        a.nombre,
        COUNT(vd.id_articulo) total
    INTO
        unoNombre,
        unoTotal
    FROM Clientes c
    INNER JOIN Ventas_cabecera vc
    ON vc.id_cliente = c.id_cliente
    INNER JOIN Ventas_detalle vd
    ON vd.id_venta_cabecera = vc.id_venta_cabecera
    INNER JOIN Articulos a
    ON vd.id_articulo = a.id_articulo
    WHERE c.nombre = nombre_cliente
    GROUP BY c.nombre, a.nombre
    ORDER BY total DESC LIMIT 1;

    SELECT
        a.nombre,
        COUNT(vd.id_articulo) total
    INTO
        dosNombre,
        dosTotal
    FROM Clientes c
    INNER JOIN Ventas_cabecera vc
    ON vc.id_cliente = c.id_cliente
    INNER JOIN Ventas_detalle vd
    ON vd.id_venta_cabecera = vc.id_venta_cabecera
    INNER JOIN Articulos a
    ON vd.id_articulo = a.id_articulo
    WHERE c.nombre = nombre_cliente
    GROUP BY c.nombre, a.nombre
    ORDER BY total ASC LIMIT 1;

    SELECT
        s.nombre
    INTO
        tresNombre
    FROM Clientes c
    INNER JOIN Ventas_cabecera vc
    ON vc.id_cliente = c.id_cliente
    INNER JOIN Sucursales s
    ON s.id_sucursal = vc.id_sucursal
    WHERE c.nombre = nombre_cliente
    GROUP BY c.nombre, s.nombre
    ORDER BY COUNT(vc.id_cliente) DESC LIMIT 1;


    SELECT
        MAX(vc.precio_total) total
    INTO
        cuatroTotal
    FROM Clientes c
    INNER JOIN Ventas_cabecera vc
    ON vc.id_cliente = c.id_cliente
    WHERE c.nombre = nombre_cliente
    GROUP BY c.nombre, vc.id_venta_cabecera
    ORDER BY MAX(vc.precio_total) DESC LIMIT 1;

    SELECT
        unoNombre
        unoTotal,
        dosNombre,
        dosTotal,
        tresNombre,
        cuatroTotal
    FROM CLIENTES
    ORDER BY unoNombre DESC LIMIT 1;
END $$

DELIMITER ;

/*
3. Generar una consulta que te permita obtener un listado 
de los artículos más y menos vendidos por sucursal  
*/
DELIMITER $$
CREATE OR REPLACE PROCEDURE Funcion3(IN orderby VARCHAR(50))
BEGIN

    SELECT 
        a.nombre,
        SUM(vd.cantidad) AS "Vendidos"
    FROM Articulos a 
    LEFT JOIN Ventas_detalle vd
    ON vd.id_articulo = a.id_articulo
    INNER JOIN Ventas_cabecera vc
    ON vc.id_venta_cabecera = vd.id_venta_cabecera
    GROUP BY a.nombre
    ORDER BY CASE WHEN orderby='ASC' THEN SUM(vd.cantidad) END,
        CASE WHEN orderby='DESC' THEN SUM(vd.cantidad) END DESC;
END $$

DELIMITER ;

/* 
4. Mostrar un listado de artículos con la siguiente información:
Clave del artículo y Nombre del artículo (En una misma columna, Marca, 
Precio unitario, Existencia, Proveedor con el que se compró por última vez, 
la cantidad que se compró y el total que se pagó en ese pedido
*/
DELIMITER $$
CREATE OR REPLACE PROCEDURE Funcion2()
BEGIN
    SELECT
        a.nombre,
        CONCAT(m.marca, ' - ', 
            a.precio_unitario, ' - ',  
            a.existencia, ' - ',
            pr.nombre, ' - ',
            pe.costo_total) 'MARCA - PRECIO UNITARIO - EXISTENCIA - PROVEEDOR - TOTAL'
    FROM Articulos a
    INNER JOIN Marcas m 
    ON a.id_marca = m.id_marca
    INNER JOIN Detalles_Pedidos dp
    ON dp.id_articulo = a.id_articulo
    INNER JOIN Pedidos pe
    ON dp.id_pedido = pe.id_pedido
    LEFT JOIN Proveedores pr
    ON dp.id_proveedor = pr.id_proveedor
    GROUP BY a.nombre, pr.id_proveedor
    ORDER BY a.id_articulo, pe.fecha_pedido ASC;
END $$

DELIMITER ;





/*
5. Generar un función que dado el nombre de un cliente, 
le modifique su porcentaje de descuento de acuerdo a 
los siguientes criterios: 
- Si ha hecho más de 15 compras 
(sin importar la cantidad de artículos o lo que ha pagado) 
un 5% del porcentaje que tiene actualmente
- Si no ha hecho compras en el último mes le reste 5% 
al porcentaje que tiene asignado (el porcentaje nunca 
puede ser negativo) 
- Si se trata del cliente con la 
compra más grande: le sume 5%
- Cabe destacar que el % de descuento nunca debe ser mayor 
al 30% y menor a 3% 
*/
/* Obtiene máximos */
DELIMITER $$
CREATE OR REPLACE PROCEDURE Funcion5(IN nombre_cliente VARCHAR(50))
BEGIN
    DECLARE uno INT unsigned DEFAULT 0;
    DECLARE dos INT unsigned DEFAULT 0;
    DECLARE tres DOUBLE unsigned DEFAULT 0.0;
    DECLARE ventagrande DOUBLE unsigned DEFAULT 0.0;
    DECLARE old DOUBLE unsigned DEFAULT 0.0;
    
    SELECT procentaje_descuento AS "Descuento"
    INTO @old
    FROM Clientes
    WHERE nombre = nombre_cliente;

    SELECT COUNT(vc.id_cliente)
    INTO @uno
    FROM Ventas_Cabecera vc
    INNER JOIN Clientes c
    ON c.id_cliente = vc.id_cliente
    WHERE c.nombre = nombre_cliente
    GROUP BY c.id_cliente;

    SELECT COUNT(vc.id_cliente)
    INTO @dos
    FROM Ventas_Cabecera vc
    INNER JOIN Clientes c
    ON c.id_cliente = vc.id_cliente
    WHERE
        c.nombre = nombre_cliente AND
        (vc.fecha BETWEEN CURRENT_DATE() AND DATE(CURRENT_DATE() - INTERVAL 1 MONTH))
    GROUP BY c.id_cliente;

    SELECT MAX(vc.precio_total)
    INTO @tres
    FROM Ventas_Cabecera vc
    INNER JOIN Clientes c
    ON c.id_cliente = vc.id_cliente
    WHERE c.nombre = nombre_cliente
    GROUP BY c.id_cliente;

    SELECT MAX(vc.precio_total)
    INTO @ventagrande
    FROM Ventas_Cabecera vc;

    IF @uno > 15 THEN
        UPDATE Clientes
        SET procentaje_descuento = 
            IF( procentaje_descuento <= 25.0,
                procentaje_descuento + 5.0,
                30.0)
        WHERE nombre = nombre_cliente;
    END IF;

    IF @dos IS NULL OR @dos = 0 THEN
        UPDATE Clientes
        SET procentaje_descuento = 
            IF( procentaje_descuento >= 8.0,
                procentaje_descuento - 5.0,
                3.0)
        WHERE nombre = nombre_cliente;
    END IF;

    IF @tres = @ventagrande THEN
        UPDATE Clientes
        SET procentaje_descuento = 
            IF( procentaje_descuento <= 25.0,
                procentaje_descuento + 5.0,
                30.0)
        WHERE nombre = nombre_cliente;
    END IF;
    
    SELECT @old "Anterior", procentaje_descuento AS "Descuento"
    FROM Clientes
    WHERE nombre = nombre_cliente;
END $$

DELIMITER ;

-- UPDATE table
-- SET A = IF(A > 0 AND A < 1, 1, IF(A > 1 AND A < 2, 2, A))
-- WHERE A IS NOT NULL;

-- Insertar Categorias --
INSERT INTO Categorias (categoria)
VALUES ('Libretas'); 
INSERT INTO Categorias (categoria)
VALUES ('Pliego de papel');
INSERT INTO Categorias (categoria)
VALUES ('Lapiz'); 
INSERT INTO Categorias (categoria)
VALUES ('Reglas');  
INSERT INTO Categorias (categoria)
VALUES ('Pegamento');

-- Insertar Marca --
INSERT INTO Marcas (marca)
VALUES ('Bip');
INSERT INTO Marcas (marca)
VALUES ('Scribe');
INSERT INTO Marcas (marca)
VALUES ('Papermate');
INSERT INTO Marcas (marca)
VALUES ('Mirado');
INSERT INTO Marcas (marca)
VALUES ('Bon');

-- Insertar Articulos --
INSERT INTO Articulos (nombre, descripcion, id_categoria, id_marca, precio_unitario, existencia)
VALUES ('Libreta Scribe', 'Libreta color verde de 100 hojas', 1, 2, 20.00, 50); 
INSERT INTO Articulos (nombre, descripcion, id_categoria, id_marca, precio_unitario, existencia)
VALUES ('Lapiz triangular', 'Lapiz mirado H2', 3, 4, 10.00, 45); 
INSERT INTO Articulos (nombre, descripcion, id_categoria, id_marca, precio_unitario, existencia)
VALUES ('Colores 24 pz', 'Lapices de colores de 24 piezas marca papermate', 3, 3, 70.20, 30); 
INSERT INTO Articulos (nombre, descripcion, id_categoria, id_marca, precio_unitario, existencia)
VALUES ('Regla estandar', 'Regla de 30 cm', 4, 1, 10.50, 40);

-- Insertar Clientes
INSERT INTO Clientes (nombre, email, rfc, procentaje_descuento)
VALUES ('Escuela Juarez', 'escuela.juarez@gmail.com', 'EDAR947910T32', 13);
INSERT INTO Clientes (nombre, email, rfc, procentaje_descuento)
VALUES ('Pimaria #2', 'primaria_numero_2@hotmail.com', 'PRIAHFN013945T', 20);
INSERT INTO Clientes (nombre, email, rfc, procentaje_descuento)
VALUES ('Municipio', 'gob.municipal@outlook.com', 'GOTIAUS2351', 0);
INSERT INTO Clientes (nombre, email, rfc, procentaje_descuento)
VALUES ('Purificadora xallapan', 'xallapan_xalapa@live.com', 'XALLAA4918235', 15);

-- Insertar domicilio --
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('152', '20 de noviembre', 'Centro', 'Xalapa', 'Veracruz - Ignacio de la llave', 'México');
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('13', 'san martin', 'los laureles', 'naranjal', 'Veracruz - Ignacio de la llave', 'México');
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('15', '21 de marzo', 'benito juarez', 'Angel R. Cabada', 'Veracruz - Ignacio de la llave', 'México');
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('253', 'san acuaman', 'arenque rojo', 'El pescadito', 'Estado pulpin', 'Atlantida');
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('742', 'Av. Siempreviva', 'Distrito 2', 'Olympia', 'Whachintong', 'EE.UU.');
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('124', 'La concha', 'Medusa loca', 'Fondo de bikini', 'Estado pulpin', 'Oceano pacifico');
INSERT INTO Domicilios (numero, calle, colonia, municipio, estado, pais)
VALUES ('4', 'San pedro', 'Lazaro Cardenas', 'Lerdo de Tejada', 'Veracruz', 'México');

-- Insertar Cliente-Docimilio --
INSERT INTO Clientes_Domicilios (id_cliente, id_domicilio)
VALUES (1, 2);
INSERT INTO Clientes_Domicilios (id_cliente, id_domicilio)
VALUES (1, 3);
INSERT INTO Clientes_Domicilios (id_cliente, id_domicilio)
VALUES (2, 4);
INSERT INTO Clientes_Domicilios (id_cliente, id_domicilio)
VALUES (3, 1);
INSERT INTO Clientes_Domicilios (id_cliente, id_domicilio)
VALUES (4, 7);
INSERT INTO Clientes_Domicilios (id_cliente, id_domicilio)
VALUES (4, 6);

-- Insertar Proveedores --
INSERT INTO Proveedores (nombre, fax, email, rfc, id_domicilio)
VALUES ('Scribe A.S', '934152051', 'scribe@gmail.com', 'SAKJ183948TF', 1);
INSERT INTO Proveedores (nombre, fax, email, rfc, id_domicilio)
VALUES ('Bip A.S', '1244182445', 'Bib@gmail.com', 'AKJSNFKJAF8759', 3);
INSERT INTO Proveedores (nombre, fax, email, rfc, id_domicilio)
VALUES ('Papermate', '150251439', 'papermate@gmail.com', 'PAKSFI583892', 6);

-- Insertar Telefonos --
INSERT INTO Telefonos (telefono)
VALUES ('5124871920');
INSERT INTO Telefonos (telefono)
VALUES ('7598316274');
INSERT INTO Telefonos (telefono)
VALUES ('9917834018');
INSERT INTO Telefonos (telefono)
VALUES ('9413274058');
INSERT INTO Telefonos (telefono)
VALUES ('2398740982');
INSERT INTO Telefonos (telefono)
VALUES ('0923589831');
INSERT INTO Telefonos (telefono)
VALUES ('9589823871');
INSERT INTO Telefonos (telefono)
VALUES ('2438479871');

-- Insertar Cliente-Telefonos --
INSERT INTO Clientes_Telefonos (id_cliente, id_telefono)
VALUES (1, 4);
INSERT INTO Clientes_Telefonos (id_cliente, id_telefono)
VALUES (1, 3);
INSERT INTO Clientes_Telefonos (id_cliente, id_telefono)
VALUES (2, 2);
INSERT INTO Clientes_Telefonos (id_cliente, id_telefono)
VALUES (3, 5);
INSERT INTO Clientes_Telefonos (id_cliente, id_telefono)
VALUES (3, 8);
INSERT INTO Clientes_Telefonos (id_cliente, id_telefono)
VALUES (4, 7);

-- Insertar Proveedores-Telefonos --
INSERT INTO Proveedores_Telefonos (id_proveedor, id_telefono)
VALUES (1, 4);
INSERT INTO Proveedores_Telefonos (id_proveedor, id_telefono)
VALUES (2, 1);
INSERT INTO Proveedores_Telefonos (id_proveedor, id_telefono)
VALUES (3, 2);
INSERT INTO Proveedores_Telefonos (id_proveedor, id_telefono)
VALUES (3, 3);

-- Insertar Sucursales --
INSERT INTO Sucursales (nombre)
VALUES ('Sucursal Aldama');
INSERT INTO Sucursales (nombre)
VALUES ('Santa Cruz');
INSERT INTO Sucursales (nombre)
VALUES ('20 de Noviembre');
INSERT INTO Sucursales (nombre)
VALUES ('Sucursal 2');
INSERT INTO Sucursales (nombre)
VALUES ('Sucursal 3');

-- Insertar Sucursal-Domicilio --
INSERT INTO Sucursales_Domicilios (id_sucursal, id_domicilio)
VALUES (1, 1);
INSERT INTO Sucursales_Domicilios (id_sucursal, id_domicilio)
VALUES (2, 2);
INSERT INTO Sucursales_Domicilios (id_sucursal, id_domicilio)
VALUES (3, 3);
INSERT INTO Sucursales_Domicilios (id_sucursal, id_domicilio)
VALUES (4, 4);
INSERT INTO Sucursales_Domicilios (id_sucursal, id_domicilio)
VALUES (5, 5);

-- Insertar Sucursal-Telefono --
INSERT INTO Sucursales_Telefonos (id_sucursal, id_telefono)
VALUES (1, 1);
INSERT INTO Sucursales_Telefonos (id_sucursal, id_telefono)
VALUES (2, 2);
INSERT INTO Sucursales_Telefonos (id_sucursal, id_telefono)
VALUES (2, 3);
INSERT INTO Sucursales_Telefonos (id_sucursal, id_telefono)
VALUES (3, 4);
INSERT INTO Sucursales_Telefonos (id_sucursal, id_telefono)
VALUES (4, 5);

-- Insertar Tipo-Pago --
INSERT INTO Tipo_Pagos (tipo_pago)
VALUES ('Efectivo');
INSERT INTO Tipo_Pagos (tipo_pago)
VALUES ('Credito');
INSERT INTO Tipo_Pagos (tipo_pago)
VALUES ('Debito');

-- Insertar Ventas_Cabecera --
INSERT INTO Ventas_Cabecera (id_cliente, id_sucursal, fecha, precio_total)
VALUES (1, 1, '04-03-2019', 140.20);
INSERT INTO Ventas_Cabecera (id_cliente, id_sucursal, fecha, precio_total)
VALUES (1, 3, '04-04-2019', 40.00);
INSERT INTO Ventas_Cabecera (id_cliente, id_sucursal, fecha, precio_total)
VALUES (2, 5, '05-03-2019', 500.00);

-- Insertar Ventas_Detalle --
INSERT INTO Ventas_Detalle (id_articulo, cantidad, precio_total_por_producto, id_venta_cabecera)
VALUES (2, 6, 60.00, 1);
INSERT INTO Ventas_Detalle (id_articulo, cantidad, precio_total_por_producto, id_venta_cabecera)
VALUES (1, 1, 20.00, 1);
INSERT INTO Ventas_Detalle (id_articulo, cantidad, precio_total_por_producto, id_venta_cabecera)
VALUES (3, 1, 70.20, 1);
INSERT INTO Ventas_Detalle (id_articulo, cantidad, precio_total_por_producto, id_venta_cabecera)
VALUES (2, 4, 40.00, 2);
INSERT INTO Ventas_Detalle (id_articulo, cantidad, precio_total_por_producto, id_venta_cabecera)
VALUES (1, 25, 500.00, 3);

-- Insertar Pedidos --
INSERT INTO Pedidos (fecha_pedido, fecha_entrega, id_tipo_pago, costo_total)
VALUES ('04-03-2019', '05-03-2019',1, 140.20);
INSERT INTO Pedidos (fecha_pedido, fecha_entrega, id_tipo_pago, costo_total)
VALUES ('05-04-2019', '06-04-2019',1, 3000.00);

-- Insert Detalle_Pedidos --
INSERT INTO Detalles_Pedidos (id_proveedor, id_articulo, cantidad, costo_total_por_producto, id_pedido)
VALUES (1, 2, 4, 300, 1);
INSERT INTO Detalles_Pedidos (id_proveedor, id_articulo, cantidad, costo_total_por_producto, id_pedido)
VALUES (1, 1, 4, 300, 1);
INSERT INTO Detalles_Pedidos (id_proveedor, id_articulo, cantidad, costo_total_por_producto, id_pedido)
VALUES (1, 2, 6, 300, 2);
INSERT INTO Detalles_Pedidos (id_proveedor, id_articulo, cantidad, costo_total_por_producto, id_pedido)
VALUES (2, 2, 4, 300, 1);
INSERT INTO Detalles_Pedidos (id_proveedor, id_articulo, cantidad, costo_total_por_producto, id_pedido)
VALUES (1, 2, 6, 200, 2);
